import { defineType, defineField } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  groups: [
    { name: "brand", title: "Brand" },
    { name: "contact", title: "Contact" },
    { name: "footer", title: "Footer" },
  ],
  fields: [
    defineField({
      name: "wordmark",
      title: "Wordmark",
      type: "string",
      group: "brand",
      description: "The firm name as it appears in the header and footer.",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "phone",
      title: "Phone (display)",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "phoneHref",
      title: "Phone (tel: link)",
      type: "string",
      group: "contact",
      description: "e.g. tel:+13145550100",
    }),
    defineField({ name: "email", title: "Email", type: "string", group: "contact" }),
    defineField({
      name: "addressLine1",
      title: "Address line 1",
      type: "string",
      group: "contact",
    }),
    defineField({
      name: "addressLine2",
      title: "Address line 2",
      type: "string",
      group: "contact",
    }),
    defineField({ name: "hours", title: "Business hours", type: "string", group: "contact" }),
    defineField({
      name: "address",
      title: "Address (structured)",
      type: "object",
      group: "contact",
      description:
        "The same address as above, split into parts so search engines can read it. Keep it in sync with the two display lines — those are what appear in the footer and contact block.",
      options: { collapsible: true, collapsed: true },
      fields: [
        {
          name: "streetAddress",
          title: "Street address",
          type: "string",
          description: 'Including any suite, e.g. "1015 Locust Street, Suite 1000".',
        },
        { name: "addressLocality", title: "City", type: "string" },
        {
          name: "addressRegion",
          title: "State",
          type: "string",
          description: 'Two-letter code, e.g. "MO".',
        },
        { name: "postalCode", title: "ZIP code", type: "string" },
        {
          name: "addressCountry",
          title: "Country",
          type: "string",
          description: 'Two-letter code, e.g. "US".',
          initialValue: "US",
        },
      ],
    }),
    defineField({
      name: "geo",
      title: "Map coordinates",
      type: "object",
      group: "contact",
      description:
        "Latitude and longitude of the office, used in structured data. Right-click the exact spot in Google Maps to read them off.",
      options: { collapsible: true, collapsed: true },
      fields: [
        { name: "latitude", title: "Latitude", type: "number" },
        { name: "longitude", title: "Longitude", type: "number" },
      ],
    }),
    defineField({
      name: "mapEmbedUrl",
      title: "Map embed URL",
      type: "url",
      group: "contact",
      description: "Google Maps embed URL. Leave blank to show a placeholder.",
    }),
    defineField({
      name: "footerBlurb",
      title: "Footer blurb",
      type: "text",
      rows: 2,
      group: "footer",
    }),
    defineField({
      name: "copyrightName",
      title: "Copyright name",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "footerColumns",
      title: "Footer columns",
      type: "array",
      group: "footer",
      of: [{ type: "footerColumn" }],
      validation: (r) => r.max(3).warning("The footer layout is designed for 3 columns."),
    }),
    defineField({
      name: "legalLinks",
      title: "Legal / bottom links",
      type: "array",
      group: "footer",
      of: [{ type: "linkItem" }],
    }),
  ],
  preview: { prepare: () => ({ title: "Site settings" }) },
});

export const navigation = defineType({
  name: "navigation",
  title: "Navigation",
  type: "document",
  fields: [
    defineField({
      name: "items",
      title: "Nav links",
      type: "array",
      of: [{ type: "linkItem" }],
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "ctaLabel",
      title: "CTA label",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "ctaHref",
      title: "CTA URL / anchor",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "portalLabel",
      title: "Client portal label",
      type: "string",
      description: "Leave empty (with the URL) to hide the client login button.",
      initialValue: "Client Login",
    }),
    defineField({
      name: "portalHref",
      title: "Client portal URL",
      type: "url",
      description: "Opens in a new tab. e.g. https://app.financial-cents.com/cp/tierneyohlms",
      initialValue: "https://app.financial-cents.com/cp/tierneyohlms",
    }),
  ],
  preview: { prepare: () => ({ title: "Navigation" }) },
});

export const homePage = defineType({
  name: "homePage",
  title: "Home page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "sections", title: "Section headers" },
    { name: "cta", title: "CTA banner" },
    { name: "contact", title: "Contact" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "hero",
      title: "Hero",
      type: "object",
      group: "hero",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        { name: "lead", title: "Lead paragraph", type: "text", rows: 3 },
        { name: "primaryCta", title: "Primary CTA", type: "cta" },
        { name: "secondaryCta", title: "Secondary CTA", type: "cta" },
        {
          name: "image",
          title: "Hero image",
          type: "image",
          options: { hotspot: true },
          fields: [
            {
              name: "alt",
              title: "Alt text",
              type: "string",
              validation: (r) => r.required(),
            },
          ],
        },
        {
          name: "strategyScene",
          title: "Tax and strategy scene",
          type: "object",
          fields: [
            { name: "eyebrow", title: "Eyebrow", type: "string" },
            { name: "heading", title: "Heading", type: "string" },
            { name: "emphasis", title: "Italic emphasized word", type: "string" },
            { name: "lead", title: "Lead paragraph", type: "text", rows: 3 },
          ],
        },
        {
          name: "artifacts",
          title: "Financial artifact content",
          type: "object",
          options: { collapsible: true, collapsed: true },
          fields: [
            { name: "monthlyCloseLabel", title: "Monthly close label", type: "string" },
            { name: "monthlyClosePeriod", title: "Monthly close period", type: "string" },
            { name: "revenue", title: "Revenue", type: "string" },
            { name: "expenses", title: "Expenses", type: "string" },
            { name: "net", title: "Net", type: "string" },
            { name: "closeSummary", title: "Close summary", type: "string" },
            { name: "automation", title: "Automation label", type: "string" },
            { name: "note", title: "Sticky note", type: "text", rows: 2 },
            { name: "cashFlowChange", title: "Cash flow change", type: "string" },
            { name: "invoiceNumber", title: "Invoice number", type: "string" },
            { name: "invoiceAmount", title: "Invoice amount", type: "string" },
            { name: "filingTitle", title: "Filing title", type: "string" },
            { name: "filingDue", title: "Filing due date", type: "string" },
            { name: "filingProgress", title: "Filing progress", type: "string" },
            { name: "reviewTitle", title: "Review title", type: "string" },
            { name: "reviewSubtitle", title: "Review subtitle", type: "string" },
            { name: "reviewTime", title: "Review time", type: "string" },
            { name: "taxSavings", title: "Tax savings", type: "string" },
          ],
        },
      ],
    }),
    defineField({
      name: "servicesHeader",
      title: "Services header",
      type: "sectionHeader",
      group: "sections",
    }),
    defineField({
      name: "whyHeader",
      title: "Why-us header",
      type: "sectionHeader",
      group: "sections",
    }),
    defineField({
      name: "processHeader",
      title: "Process header",
      type: "sectionHeader",
      group: "sections",
    }),
    defineField({
      name: "faqHeader",
      title: "FAQ header",
      type: "sectionHeader",
      group: "sections",
    }),
    defineField({
      name: "ctaBanner",
      title: "CTA banner",
      type: "object",
      group: "cta",
      fields: [
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        { name: "lead", title: "Lead", type: "text", rows: 2 },
        { name: "cta", title: "Button", type: "cta" },
      ],
    }),
    defineField({
      name: "contact",
      title: "Contact",
      type: "object",
      group: "contact",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        {
          name: "emphasis",
          title: "Emphasised phrase",
          type: "string",
          description:
            'The part of the heading shown in gold italic — copy it exactly as it appears in the heading, e.g. "message." Leave blank for no emphasis.',
        },
        { name: "lead", title: "Lead", type: "text", rows: 2 },
        {
          name: "serviceOptions",
          title: "Service dropdown options",
          type: "array",
          of: [{ type: "string" }],
        },
      ],
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Home page" }) },
});


export const aboutPage = defineType({
  name: "aboutPage",
  title: "Our Story page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "story", title: "The story" },
    { name: "rooted", title: "Rooted in St. Louis" },
    { name: "founders", title: "Founders" },
    { name: "promises", title: "What we promise" },
    { name: "firstClient", title: "First client" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "hero",
      title: "Hero",
      type: "object",
      group: "hero",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        { name: "lead", title: "Lead paragraph", type: "text", rows: 3 },
      ],
    }),
    defineField({
      name: "story",
      title: "The story",
      type: "object",
      group: "story",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        {
          name: "body",
          title: "Body",
          type: "text",
          rows: 12,
          description: "Separate paragraphs with a blank line.",
          validation: (r) => r.required(),
        },
      ],
    }),
    defineField({
      name: "rooted",
      title: "Rooted in St. Louis",
      type: "object",
      group: "rooted",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        {
          name: "heading",
          title: "Heading",
          type: "string",
          validation: (r) => r.required(),
        },
        {
          name: "body",
          title: "Body",
          type: "text",
          rows: 8,
          description: "Separate paragraphs with a blank line.",
        },
        {
          name: "pullQuote",
          title: "Pull quote",
          type: "text",
          rows: 2,
          description: "The highlighted callout line beside the copy.",
        },
      ],
    }),
    defineField({
      name: "founders",
      title: "Founders",
      type: "object",
      group: "founders",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        { name: "heading", title: "Heading", type: "string" },
        {
          name: "people",
          title: "People",
          type: "array",
          of: [{ type: "founder" }],
          validation: (r) => r.max(4),
        },
      ],
    }),
    defineField({
      name: "promises",
      title: "What we promise",
      type: "object",
      group: "promises",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        { name: "heading", title: "Heading", type: "string" },
        {
          name: "items",
          title: "Promises",
          type: "array",
          of: [{ type: "string" }],
        },
      ],
    }),
    defineField({
      name: "firstClient",
      title: "The first client",
      type: "object",
      group: "firstClient",
      fields: [
        { name: "eyebrow", title: "Eyebrow", type: "string" },
        { name: "heading", title: "Heading", type: "string" },
        {
          name: "body",
          title: "Body",
          type: "text",
          rows: 8,
          description: "Separate paragraphs with a blank line.",
        },
      ],
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
  ],
  preview: { prepare: () => ({ title: "Our Story page" }) },
});
